spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://47.243.107.204:3306/ym
          username: happyfarm
          password: 123456
          driver-class-name: com.alibaba.druid.proxy.DruidDriver
        slave_1:
          url: jdbc:mysql://127.0.0.1:3307/ym
          username: happyfarm
          password: 123456
          driver-class-name: com.alibaba.druid.proxy.DruidDriver
#        slave_2:
#          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
#          username: ENC(xxxxx)
#          password: ENC(xxxxx)
#          driver-class-name: com.mysql.jdbc.Driver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2
